#! /bin/bash

for arg in "$@" ; do
  # This first clause is redundant with the third, but hedging on portability
  if [ "$arg" = "-v" ] || [ "$arg" = "--verbose" ] || echo "$arg" | grep -E -- "-v+$" ; then
    VERBOSE=1
  fi
done

XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
VENV_NAME="mitnk.github.io"
VENV_PATH=${VENV_PATH:-"$XDG_DATA_HOME/$VENV_NAME"}
VENV_BIN=${VENV_PATH}/bin
FILE_REQUIREMENTS="./requirements.txt"


if [ ! -d $VENV_PATH ]; then
  printf "Creating virtual environment at $VENV_PATH"
  python3 -m venv $VENV_PATH

  if [ -f "${FILE_REQUIREMENTS}" ]; then
    while read p; do
      $VENV_BIN/pip install $p
    done < "${FILE_REQUIREMENTS}"
  else
    echo "Error: ${FILE_REQUIREMENTS} does not exist"
    exit 1
  fi

  printf "ok\n"
fi


COMPILER="./compile.py"
for doc in $(git status | grep -o '_src\/docs\/.*\.md$') ; do
    if [ "$VERBOSE" = 1 ] ; then
      echo "Running: $VENV_BIN/python \"${COMPILER}\" \"${doc}\""
    fi
    $VENV_BIN/python "${COMPILER}" -f "${doc}"
done
